### ISSUE TITLE
Evaluation system confusion

### ISSUE THREAD

**Issue by RumblingTurtle** [Hilti-Research/hilti-slam-challenge-2023#6]
I've noticed that if you take a single session trajectory and rotate it the score changes. Shouldn't the score of the resulting trajectory be invariant to homogeneous transformation?

**Comment by hilti-challenge** [comment]
Hi @RumblingTurtle,

Thanks for reaching out!
Kindly send us your team name and submission number(s) so we can take a closer look into what's causing this.

Best,
The Hilti SLAM Challenge Team.

**Comment by plamenl** [comment]
Hello,
You are correct that homogeneous rotations should not affect the score.
However it seems that applying either your rotation , or any arbitrary rotation does not change the score for either of these trajectories.
Is it possible there are some subtle differences between your trajectories? For example we noticed that the timestamp precision is different in the two files. While this doesn't seem to have any effect, it suggests there might be some other minor changes? Or the rotation introduced some sort of precision issues ?

Best,
The Hilti SLAM Challenge Team.

**Comment by RumblingTurtle** [comment]
Thank you for replying. We checked the scoring system once again on submissions 52 and 53 of "Strelka" team

1) We used timestamps and coordinates with the same precision
2) Submission 52 was rotated by 90 degrees around the Z axis to produce submission 53.

Such rotation would simply turn X into -Y and Y coordinate into X. So the only difference is the change of axis with proper sign. You can double check that by looking at the trajectory files. Despite that the scores still differ

**Comment by plamenl** [comment]
Hello,
Thanks again for bringing this to our attention.
As it turns out the transformation does matter. This is due to the fact that we apply a rigid body transformation on the poses to account for the IMU's placement on the system.
Therefore rotating the trajectory before this transformation produces different results. 
When we looked at the issue earlier we only applied rotations right before alignment with the reference points, so apologies for the confusion.
Please submit the trajectories only in the IMU coordinate frame. We are going to update the FAQ to be more clear on this.

Best,
The Hilti SLAM Challenge Team.

**Comment by RumblingTurtle** [comment]
Everything now seems clear. Thank you very very much
