### ISSUE TITLE
Whats up with the leaderboards?

### ISSUE THREAD

**Issue by schablonmassig** [Hilti-Research/hilti-slam-challenge-2023#9]
The public release of the leaderboards has been delayed multiple times by now. Whats up?

**Comment by hilti-challenge** [comment]
Hi @schablonmassig,
Thanks for your message. We're a bit delayed on our leaderboards since we didn't have an automated notification to participants this year, and I haven't mailed every participant yet. Once that's out and we have feedback from those who wish to not disclose their team name, it gets published.

Sorry about the inconvenience, our timeline needed to be extended.
Shall close the github issue once it's out.

Ashish 
The Hilti SLAM Challenge Team

**Comment by YoshuaNava** [comment]
Hi,
Last year it was an excellent experience to participate in the challenge, because we A) Got a great overview of the technological landscape in SLAM, B) Measured our system using the automated evaluation system and awesome datasets, and C) Found out what we needed to improve to push its performance to a higher level. Furthermore, it was quite awesome to see the "heavy weights" like CSIRO and HKU-MARS participating. They are the leaders in the field, the ones that are defining the way forward.

This year I had a strong feeling that the emphasis was put on the winning teams, giving prizes to academic participants, and the final presentation at ICRA23 didn't give any insights on the technological landscape, on how the scores were spread based on the methods used, etc. While I appreciate a lot the great organization I feel the later aspect is currently missing.

(I'm giving this feedback in good faith and in a friendly manner)

Best regards,
Yoshua
